### ISSUE TITLE
Change/Update the product amount by using '+' or '-' button

### ISSUE THREAD

**Issue by IreneYIN7** [CSCI-GA-2820-FA23-003/shopcarts#1]
**As** a User
**I need** to be able to reduce or increase the amount of a product.
**So that** I could modify the amount of a product I want to buy from the shop cart.
   
 ### Details and Assumptions
Assumption: Assume there is a product that I want to reduce or increase its amount in the shop cart.
Details:
1. If I want to reduce the number of the product, I could click the '-' button. 
2. Else if I want to increase the number of amounts of the product, I could click the '+' button.
 
 ### Acceptance Criteria  
   
 ```gherkin
 Given there is a specific product that I want to change the amount of,
 When I click '+' or '-' button,
 Then I can increase or decrease the amount of this product from the shop cart.
```

**Comment by sahishnu** [comment]
@IreneYIN7 I think this assumes some sort of UI to interact with the service. Are we building a UI? I thought we are just building the API services. So there wouldnt be any buttons or inputs. Just RESTful calls, like using Postman or something

cc @jjrofrano

**Comment by rofrano** [comment]
@IreneYIN7 You will be building a UI in the 2nd half of the semester but for now you are correct in that you are building the backend REST API that the frontend UI will eventually call.

**Comment by IreneYIN7** [comment]
@sahishnu I see. Thanks for pointing this out! 
@jjrofrano Thanks a lot for the clarifications. 
Since the UI would be 2nd half of the semester, I wonder if I need to delete it or let it lay down here util we reach to UI part?
