### ISSUE TITLE
Update a Customer's Shopcart (PUT)

### ISSUE THREAD

**Issue by gary1209** [CSCI-GA-2820-FA23-003/shopcarts#11]
**As a** customer,
**I need** the ability to update the items in my shopping cart
**So that** I can modify my purchase before finalizing it

### Details and Assumptions:
- The customer has a shopping cart with items.
- The customer can update the quantity or remove items from the cart.
- Any changes made to the cart should be reflected in the cart's total price.

### Acceptance Criteria:
```gherkin
Given a customer id, product id, and updated item quantity,
When a PUT request is made to /shopcarts/{customer_id}/{product_id}?quantity={updated_quantity},
Then the item quantity in the customer's shop cart should be updated accordingly,
And the cart's total price should be recalculated.
```

**Comment by IreneYIN7** [comment]
@gary1209 I think this is the same as issue 7.

**Comment by gary1209** [comment]
duplicate to issue #7
