### ISSUE TITLE
Delete a Customer's Shopcart (DELETE)

### ISSUE THREAD

**Issue by gary1209** [CSCI-GA-2820-FA23-003/shopcarts#12]
**As a** customer,
**I need** the ability to delete my entire shopping cart
**So that** I can start fresh or cancel my current purchase
   
 ### Details and Assumptions
 * The customer has a shopping cart with items.
 * Deleting the cart should remove all items within it.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a customer id,
When a DELETE request is made to /shopcarts/{customer_id},
Then the customer's entire shopping cart should be deleted,
And all items within the cart should be removed from the system.
```

**Comment by IreneYIN7** [comment]
@gary1209 I think this is the same as issue 10.

**Comment by gary1209** [comment]
duplicate to issue #10
