### ISSUE TITLE
Update `test_routes.py` that includes tests for each of our service routes (CRUD)

### ISSUE THREAD

**Issue by IreneYIN7** [CSCI-GA-2820-FA23-003/shopcarts#13]
**As a** Developer
**I need** to test our service routes by generating test cases that cover at least 95% of our code,
**So that** we make sure that it won't crash when published. 
   
 ### Details and Assumptions
1. Must have 95% code coverage, Use the coverage tool to measure test coverage.
2. There should be tests for each of our service routes, traversing both happy paths and sad paths.
3. Run these tests using green as you develop the code making them all green (passing).
4. Use the standard PyUnit syntax that we learned.
5. place your test cases in a `./tests` folder.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service routes,
 When we run Unit tests that cover at least 95% of our code in `test_routes.py`,
 Then all Unit tests are passed.

**Comment by sahishnu** [comment]
The work for this story should be completed as part of all stories that create routes. Developers should write tests & documentation along with their code!
