### ISSUE TITLE
Update `test_models.py` that includes tests for our models

### ISSUE THREAD

**Issue by IreneYIN7** [CSCI-GA-2820-FA23-003/shopcarts#14]
**As a** Developer
**I need** to write Unit tests to test our backend models created,
**So that** we make sure that our models and methods are functioning as desired.
   
 ### Details and Assumptions
1. Must have 95% code coverage, Use the coverage tool to measure test coverage.
2. There should be tests for each of Create, Read, Update, Delete, and List, traversing both happy paths and sad paths.
3. Run these tests using green as you develop the code making them all green (passing).
4. Use the standard PyUnit syntax that we learned.
5. place your test cases in a ./tests folder.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the models,
 When we run Unit tests which cover at least 95% of our code,
 Then all Unit tests are passed. 
```

**Comment by sahishnu** [comment]
This is completed by #6.
