### ISSUE TITLE
Allow Customers Checkout with Selected Items

### ISSUE THREAD

**Issue by kriszhli** [CSCI-GA-2820-FA23-003/shopcarts#16]
**As a** customer
**I need** the ability to proceed to the checkout page with the selected items
**So that** I can complete my order
   
 ### Details and Assumptions
 * There exists a shopcart with items associated with a customer
 * Customers can select the items they want to purchase with checkboxes
 * Customers can proceed to the checkout page with their selected items
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a customer with items in their shopcart,
 When the customer select at least one item in their shopcart,
 Then the "Proceed to Checkout" button linked to the checkout page should be clickable
```

**Comment by sahishnu** [comment]
This story may belong to the **ORDERS** team.

**Comment by kriszhli** [comment]
Yes but I am confused if we need to setup pipelines to transfer information to the orders team, and similarly, to the wishlists team.

**Comment by kriszhli** [comment]
Yes but I am confused if we need to setup pipelines to transfer information to the orders team, and similarly, to the wishlists team.
