### ISSUE TITLE
Change/Update the amount of the products in the shop cart by typing in direct amount

### ISSUE THREAD

**Issue by IreneYIN7** [CSCI-GA-2820-FA23-003/shopcarts#3]
**As a** User,
**I need** to be able to change the amount of product I added to the shop cart,
**So that** I could buy the desired amount of product.
   
 ### Details and Assumptions
Assumption: Assume there is a product that I want to change its amount in the shop cart.
When a user adds a product to the shop cart, the default number would be 1. If users want to buy 5 of that product, they could directly change the number by typing in the amount in the amount box.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there is a product in the shop cart,
 When a user modifies the amount of product by typing a number in the amount box,
 Then the amount of product in the shop cart would change to the user's desired amount.
```

**Comment by sahishnu** [comment]
This ticket can be picked up when UI work is started
