### ISSUE TITLE
[COPY OF] Set Up GitHub Actions for Running Unit Tests

### ISSUE THREAD

**Issue by gary1209** [CSCI-GA-2820-FA23-003/shopcarts#60]
**As a** developer
**I need** I need to set up GitHub Actions to run unit tests every time someone pushes to the master branch or submits a Pull Request
**So that** So that I can ensure the code is tested automatically and identify issues early.
 
Details and Assumptions
* All the while maintaining 95%+ code coverage

 ### Acceptance Criteria  
   
 ```gherkin
Given the GitHub repository for the project
When code is pushed to the master branch or a Pull Request is submitted
Then GitHub Actions should automatically trigger and run the unit tests using the specified command.
```

**Comment by sahishnu** [comment]
This story is completed by https://github.com/CSCI-GA-2820-FA23-003/shopcarts/issues/18
